"use strict";var u=Object.create;var d=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var T=Object.getOwnPropertyNames;var x=Object.getPrototypeOf,v=Object.prototype.hasOwnProperty;var l=(o,t,c,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let m of T(t))!v.call(o,m)&&m!==c&&d(o,m,{get:()=>t[m],enumerable:!(n=r(t,m))||n.enumerable});return o};var i=(o,t,c)=>(c=o!=null?u(x(o)):{},l(t||!o||!o.__esModule?d(c,"default",{value:o,enumerable:!0}):c,o));var e=i(require("vscode")),w=i(require("path")),s=i(require("fs"));var a=w.join(__dirname,"test-output.md");suite("Markly - 100% \u529F\u80FD\u8986\u76D6\u6D4B\u8BD5",()=>{suiteSetup(()=>{s.writeFileSync(a,`# Test

`,"utf-8")}),suiteTeardown(()=>{s.existsSync(a)&&s.unlinkSync(a)}),setup(async()=>{s.writeFileSync(a,`# Test

`,"utf-8")}),test("1.1 \u5207\u6362\u5230\u9884\u89C8\u6A21\u5F0F",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("1.2 \u5207\u6362\u5230\u6E90\u7801\u6A21\u5F0F",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,2e3)),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,2e3))}),test("2.1 \u64A4\u9500\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3)),await e.commands.executeCommand("markly.undo").catch(()=>{})}),test("2.2 \u91CD\u505A\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3)),await e.commands.executeCommand("markly.redo").catch(()=>{})}),test("3.1-3.6 \u6807\u9898\u5FEB\u6377\u952E",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(c=>setTimeout(c,3e3));let t=await e.commands.getCommands()}),test("4.1-4.8 \u683C\u5F0F\u5316\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("5.1-5.6 \u5217\u8868\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("6.1-6.8 \u63D2\u5165\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("7.1 \u67E5\u627E\u66FF\u6362\u9762\u677F",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("8.1 \u5927\u7EB2\u9762\u677F",async()=>{s.writeFileSync(a,`# Title 1

## Title 2

### Title 3`,"utf-8");let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("9.1 \u5B57\u6570\u7EDF\u8BA1",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("10.1 \u6E90\u7801\u6A21\u5F0F\u7F16\u8F91",async()=>{let o=await e.workspace.openTextDocument(a);if(await(await e.window.showTextDocument(o)).edit(n=>{n.insert(new e.Position(0,0),`# New Title

`)}),await e.commands.executeCommand("workbench.action.save"),await new Promise(n=>setTimeout(n,1e3)),!s.readFileSync(a,"utf-8").includes("New Title"))throw new Error("\u4FDD\u5B58\u5931\u8D25")}),test("11.1 \u5BFC\u51FA PDF",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.export.pdf"),await new Promise(t=>setTimeout(t,5e3))}),test("11.2 \u5BFC\u51FA HTML",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.export.html"),await new Promise(t=>setTimeout(t,3e3))}),test("11.3 \u5BFC\u51FA\u56FE\u7247",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.export.image").catch(()=>{}),await new Promise(t=>setTimeout(t,3e3))}),test("12.1-12.3 \u5FEB\u6377\u952E\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("13.1 \u4E3B\u9898\u529F\u80FD",async()=>{let o=await e.workspace.openTextDocument(a);await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3))}),test("14.1 \u56FE\u7247\u9884\u89C8",async()=>{let o=w.join(w.dirname(a),"test.png");s.writeFileSync(o,Buffer.alloc(100));let t=await e.workspace.openTextDocument(a);await e.window.showTextDocument(t),await e.commands.executeCommand("markly.toggleMode"),await new Promise(c=>setTimeout(c,3e3)),s.existsSync(o)&&s.unlinkSync(o)}),test("15.1 \u5B8C\u6574\u7528\u6237\u6D41\u7A0B",async()=>{let o=await e.workspace.openTextDocument(a);if(await e.window.showTextDocument(o),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,3e3)),await e.commands.executeCommand("markly.toggleMode"),await new Promise(t=>setTimeout(t,2e3)),await e.commands.executeCommand("workbench.action.save"),await new Promise(t=>setTimeout(t,1e3)),!s.existsSync(a))throw new Error("\u6D4B\u8BD5\u6587\u4EF6\u4E22\u5931")})});
